version: '3'
services:
  semantic-data-catalog-frontend:
    build: ./frontend
    container_name: semantic_data_catalog_frontend
    volumes:
      - "./frontend:/app/frontend:delegated"
      - "/app/frontend/node_modules"
    stdin_open: true
    environment:
      - REACT_APP_OIDC_ISSUER=https://solidcommunity.net
    tty: true
    ports:
      - "5000:5000"

  semantic-data-catalog-fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    hostname: fuseki  
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - fuseki_data:/fuseki

    ports:
      - "3030:3030"

volumes:
  node_modules:
  fuseki_data:
